# Generated by Django 5.2.7 on 2025-11-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcadia_app', '0002_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.DateTimeField(),
        ),
    ]
