# Generated by Django 5.2.7 on 2025-11-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcadia_app', '0003_alter_event_event_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=20)),
                ('people', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
