# Generated by Django 5.2.7 on 2025-11-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcadia_app', '0004_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
